# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Android Build CD

on:
  push:
    branches: [ "android" ]

jobs:
  build-ionic:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm install -g @ionic/cli
    - run: ionic build
    - run: npx cap add android
    - run: npx cap sync
    - run: ls android/
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Uninstall  build-tool version 31.0.0
      run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager --uninstall 'build-tools;31.0.0'

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: Build with Gradle
      run: |
        cd android
        ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: androidAPK
        path: ./android/app/build/outputs/apk
